Sprint 1 step 1
StakisL/react-burger pull request #1
Opened 2022-10-02 10:38 UTC by StakisL

2022-10-30 18:32 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа. Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;

### **Но есть несколько замечаний, которые нужно исправить:**

- Не запускается проект. Чтобы это проверить, склоньтесь со своего репозитория, и попробуйте запустить проект.

- Проект должен находиться в корне репозитория, а не в отдельной папке.

- Нужно очистить корневую директорию от лишних файлов, которые остались при инициализации create-react-app.

- Поправить работу с propTypes. Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-10-30 18:32 UTC, ArslanDev666 commented on react-burger/src/components/burger-ingredients/burger-ingredients.jsx
> +});
**Надо исправить:** У ингредиента немного больше полей. А также лучше вынести его в отдельный файл (можно создать файл prop-types.js в корне src) и переиспользовать описание пропсов ингрединта, а не дублировать, его во многих компонентах.

```js
_id: PropTypes.string.isRequired,
name: PropTypes.string.isRequired,
type: PropTypes.oneOf(["bun", "main", "sauce"]).isRequired,
proteins: PropTypes.number.isRequired,
fat: PropTypes.number.isRequired,
carbohydrates: PropTypes.number.isRequired,
calories: PropTypes.number.isRequired,
price: PropTypes.number.isRequired,
image: PropTypes.string.isRequired,
image_large: PropTypes.string.isRequired,
image_mobile: PropTypes.string.isRequired,
```

2022-10-30 18:32 UTC, ArslanDev666 commented on react-burger/src/components/burger-ingredients/burger-ingredients.jsx
> +    const bun = props.data.filter(x => x.type === 'bun');
**вы молодец:** Здесь и далее. Отличная реализация, но тут лучше явно указывать название, `ingredient` вместо `x`.

2022-10-30 18:32 UTC, ArslanDev666 commented on react-burger/src/components/burger-ingredients/burger-ingredients.jsx
> +                    <Tab value="bun" active={true} onClick={currentHandle("bun")}>
**можно лучше:** Сделайте проверку в пропсе `active`, Например: 

```js
active={current === 'bun'}.
```

А также тут можно просто написать currentHandle, без параметров, т.к этот компонент сам прокинет значение с value (Обратите внимание на пропс onClick).

2022-10-30 18:32 UTC, ArslanDev666 commented on react-burger/src/components/burger-constructor/burger-constructor.jsx
> +const burgerPropTypes = PropTypes.shape({
**Надо исправить:** Описал похожую проблему в `burger-ingredients`.

2022-10-30 18:32 UTC, ArslanDev666 commented on react-burger/src/components/ingredients-list/ingredients-list.jsx
> +const ingredientPropTypes = PropTypes.shape({
**Надо исправить:** Описал похожую проблему в `burger-ingredients`.

2022-10-30 18:32 UTC, ArslanDev666 commented on react-burger/src/components/burger-constructor/burger-constructor.jsx
> +
**Надо исправить:** `useEffect`, немного не для этого предназначен. Сумму лучше считать в переменной, а после (когда изучите `useMemo`), обернуть в `useMemo`.

2022-10-30 18:32 UTC, ArslanDev666 commented on react-burger/src/components/burger-constructor/burger-constructor.jsx
> +    data: PropTypes.arrayOf(burgerPropTypes).isRequired
**Надо исправить:**

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.

2022-10-30 18:32 UTC, ArslanDev666 commented on react-burger/src/components/burger-constructor/burger-constructor.jsx
> +    const bottomBun = props.data.findLast(x => x.type === 'bun')
**Можно лучше:** немного не понимаю, у нас булка всегда будет одна и та же, зачем нам искать её второй раз :?

2022-10-30 18:32 UTC, ArslanDev666 commented on react-burger/src/components/burger-ingredients/burger-ingredients.jsx
> +BurgerIngredients.propTypes = {
**Надо исправить:**

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.

2022-10-30 18:32 UTC, ArslanDev666 commented on react-burger/src/components/ingredients-list/ingredients-list.jsx
> +    ingredients: PropTypes.arrayOf(ingredientPropTypes).isRequired
**Надо исправить:**

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в PropTypes.

2022-10-30 18:48 UTC, StakisL commented on react-burger/src/components/burger-constructor/burger-constructor.jsx
> +    const bottomBun = props.data.findLast(x => x.type === 'bun')
Привет, вот тут чутка не согласен. Не было описана работа апи и дан только json c массивом, видов булки 2, я предположил, что может быть так, что первым элементом массива может прийти одна булка, а последним другая. Например, у бургера сверху голубая булка, а снизу фиолетовая

2022-10-31 03:59 UTC, StakisL commented on react-burger/src/components/burger-ingredients/burger-ingredients.jsx
> +                    <Tab value="bun" active={true} onClick={currentHandle("bun")}>
`<Tab value="bun" active={current === 'bun'} onClick={currentHandle()}>
                      Булки
                    </Tab>`
Такой код у меня не работает, а если пробрасывать параметр, тогда все отлично

2022-10-31 04:28 UTC, ArslanDev666 commented on react-burger/src/components/burger-constructor/burger-constructor.jsx
> +    const bottomBun = props.data.findLast(x => x.type === 'bun')
Это круто, что вы рассматриваете разные кейсы) но в данном случае былка всё же будет 1 и та же всегда  :(

2022-10-31 04:45 UTC, StakisL commented
Оставлю тут пункты по ревью которые были не совсем понятны:
1.  В общем комментарии сначала написано, что я молодец, проект запускается и работает без ошибок, а в замечаниях написано, что он не работает. (предположу что там была проблема с npm start, но после того как я вынес файлы в корневую директорию проблема ушла)
2. `Нужно очистить корневую директорию от лишних файлов, которые остались при инициализации create-react-app.` - я не совсем понял о чем идет речь, из таких файлов максимум, что нашел это дефолтные тесты, их удалил, если это не они, пожалуйста, уточните на втором ревью о каких файлах речь.
Спасибо)

2022-10-31 06:48 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа. Практически все замечания с прошлого ревью были исправлены.

По поводу ваших вопросов:

1. Если ошибок не так много, и их можно быстро исправить, я не считаю что эта работа не запускается. Если бы всё было очень плохо, я бы вернул работу без проверки, без потери итерации.

2. Да, вы всё верно сделали.

### **Вы молодец! Можете приступать к финальной части задания.**

### **Есть несколько замечаний, которые нужно исправить:**

-   Поправит propTypes. Отметил в коде.

-   Исправьте ошибки в консоли: https://yadi.sk/i/3SQYq8p1y2F9wg.

### **Сделает код лучше:**

-   prop-types.jsx - лучше переместить в папку utils. Знаю что прошлый раз сказал про корень, в целом это вообще не критично, поэтому тут по желанию.

-   При клике на соответвующий таб должен происходить скролл к нужному разделу в списке ингредиентов

    Для этого можно задать каждому заголовку соотвующий id (или использовать refы) и вызывать scrollIntoView
    Например:

    ```
      const setTab = (tab) => {
        setCurrent(tab);
        const element = document.getElementById(tab);
        if (element) element.scrollIntoView({ behavior: "smooth" });
      };

    ```

    где заголовкам разделов заданы соответсвующие атрибуты id
    https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView.

    Но я всё таки рекомендую делать скролл не через `id`, а через ref'ы. Потому что рефы намного быстрее работают, чем поиск элемента по id.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-10-31 06:48 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +		return sum
**Можно лучше:** вот тут лучше использовать метод reduce. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

2022-10-31 06:48 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +					text={bun.name}
**Надо исправить:** У булок должна быть приписка: `(верх) и (низ)`. Это можно увидеть на макете.

2022-10-31 06:48 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +}
**Надо исправить:** не совсем понял, зачем тут 2 раза 1 и тот же пропс, описывается. Вот такой вариант будет правильным: 

```js
data: PropTypes.arrayOf(burgerPropTypes.isRequired).isRequired,
```
И элемент `.isRequired` и массив)

2022-10-31 06:48 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +BurgerIngredients.propTypes = {
**Надо исправить:** Описал похожее замечание в `burger-constructor`.

2022-10-31 06:48 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +	const currentHandle = (val) => () => setCurrent(val)
**Надо исправить:** Тут лучше сделать обычную функцию, а не каррирование. 

```js
	const currentHandle = (val) => {
    // какие-то дейстивия, например скролл к разделу.
    setCurrent(val)
  }

  // Пример  импользования.
<Tab value="bun" active={current === 'bun'} onClick={currentHandle}>
  Булки
</Tab>

```

2022-10-31 06:48 UTC, ArslanDev666 commented on src/components/ingredients-list/ingredients-list.jsx
> +	ingredients: PropTypes.arrayOf(burgerPropTypes).isRequired,
**Надо исправить:** Описал похожее замечание в `burger-constructor`.

2022-11-07 18:43 UTC, merged