Sprint 1 step 2
StakisL/react-burger pull request #2
Opened 2022-11-01 07:01 UTC by StakisL

2022-11-05 19:56 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

### **Но есть несколько замечаний, которые нужно исправить:**

-   Верстка OrderDetails и IngredientDetails не соответствует макету,
    сверьтесь с макетом:

    -   https://disk.yandex.ru/d/yMtWaT2MUb6jJw
    -   https://yadi.sk/d/9DKh9eCHXtlFhg

-   Поправьте логику работы модальных окон.

-   Поправьте работу с сервером.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-11-05 19:56 UTC, ArslanDev666 commented on src/components/app/app.jsx
> +const urlApi = 'https://norma.nomoreparties.space/api/ingredients'
**Надо исправить**
вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

2022-11-05 19:56 UTC, ArslanDev666 commented on src/components/app/app.jsx
> +			.finally(() => setLoaded(true))
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```js
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответит не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```js
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```js
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2022-11-05 19:56 UTC, ArslanDev666 commented on src/components/app/app.jsx
> +	} else {
При использовании return внутри `if`, оператор `else` можно опустить, т.к. если `if` выполнится, то будет возврат из функции и код под блоком `if` выполнен	не будет:
```
	if (someCondition) {
		return value;
	}
	return data;
```
Такой подход называется "ранний возврат" https://habr.com/ru/post/348074/

2022-11-05 19:56 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +	const ingredients = props.data.filter((element) => element.type !== 'bun')
**Можно лучше:** Здесь и в похожих местах. Такие вычисления лучше обернуть в useMemo. Чтобы не было перерасчёта при ререндере компонента

2022-11-05 19:56 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +				<Modal type="order-details" isOpen={isOpen} handleClose={handleClose} />
**Надо исправить:**

не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

```js
{isOpen && (
    компонент открываемого попапа
)}
```

А также компонент модального окна не должен знать о том, что в нём будет открыто. Поэтому контент нужно передавать через `children`.
```js
<Modal {/** ... */}>
  <OrderDetails />
<Modal/>  
```

2022-11-05 19:56 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +				<Button htmlType="button" type="primary" size="medium" onClick={() => setOpen(true)}>
**Можно лучше:**

Лучше вынести обработчик событий в отдельную функцию.

2022-11-05 19:56 UTC, ArslanDev666 commented on src/components/burger-ingredient/burger-ingredient.jsx
> +			<Modal type="ingredient" ingredient={props.ingredient} isOpen={isOpen} handleClose={handleClose} />
**Надо исправить:**

Отметил похожую проблему в `burger-constructor`.

**Можно лучше:** 

Модальное окно лучше переместить в компонент `burger-ingredients`.

2022-11-05 19:56 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +			if (e.keyCode === 27) {
**Надо исправить**

вынесите магическое значение 27 в именованную константу `const ECK_KEYCODE = 27`

2022-11-05 19:56 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +				<ModalOverlay handleClose={props.handleClose}>
**Надо исправить**

у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер.

Ниже показана правильная структура компонента `Modal`.
```js
<>
  <div className={styles.modal}> {/** ... */} <div>
  <ModalOverlay onClick={onClose} />
</>
```

2022-11-05 19:56 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +	return props.isOpen
**Надо исправить**

не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

```js
{isOpen && (
    компонент открываемого попапа
)}
```

2022-11-05 19:56 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +							)}
**Надо исправить:** Т.к модальный окон может быть очень много, то контент для них нужно передавать именно в children.

2022-11-05 19:56 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +				document.body,
**Надо исправить:** У модального окна должен быть свой DOM элемент: 

```js
const modalRoot = document.getElementById('modals');
```

Лучше вынести переменную за пределы компонента.

2022-11-06 09:48 UTC, StakisL commented on src/components/burger-ingredient/burger-ingredient.jsx
> +			<Modal type="ingredient" ingredient={props.ingredient} isOpen={isOpen} handleClose={handleClose} />
Не согласен с `Модальное окно лучше переместить в компонент burger-ingredients.`
В данном случае, модальное окно показывает описание конкретного ингредиента и должно вызываться для конкретного ингредиента, в этом же и фишка createPortal что нам не важно из какого места вызывать окно, оно будет вне дерева.

А если я отнесу это в burger-ingredients у него другая ответственность, да и в целом он даже не знает какой ингредиент я выбрал.

2022-11-06 09:50 UTC, StakisL commented on src/components/burger-ingredient/burger-ingredient.jsx
> +			<Modal type="ingredient" ingredient={props.ingredient} isOpen={isOpen} handleClose={handleClose} />
Возможно, если бы я архитектурно по другому построил приложение и все взаимодействие с ингредиентами было в одном месте, тогда это бы имело смысл

2022-11-06 10:38 UTC, StakisL commented on src/components/modal/modal.jsx
> +				<ModalOverlay handleClose={props.handleClose}>
@ArslanDev666, а можно уточнения почему моя реализация не правильная? Дело в том, что я задал вопрос в слаке и старший студент сказал, что такая реализация по крайней мере раньше считалась верной

2022-11-06 10:52 UTC, StakisL commented on src/components/modal/modal.jsx
> +				<ModalOverlay handleClose={props.handleClose}>
https://blog.logrocket.com/build-modal-with-react-portals/#creating-react-portal

Тут описывают так же как сделал я, возможно чуть более изыскано, но кажется это точно такая же подложка через  wrapper

2022-11-07 05:13 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Практически все замечания с прошлого ревью были исправлены.

### **Вы молодец!**

### **Но есть 1 замечание, которое нужно исправить:**

-   Поправьте логику работы модальных окон:

    -   Не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-11-07 05:13 UTC, ArslanDev666 commented on src/components/app-header/app-header.jsx
> +						<a className={headerStyles.nav_link} href="1">
**Надо исправить:** 

По макету у вас должна быть активна первая ссылка.

2022-11-07 05:13 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +	}, [props])
**Надо исправить:** 

Нужно деструктурировать пропсы, и указать здесь только те, которые используются в useEffect, либо пустой массив. Иначе, у вас будет срабатывать код каждый раз при изменении любого значения из пропсов.

2022-11-07 05:13 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +			{props.isOpen &&
**Надо исправить:**

Не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

```js
{isOpen && (
    компонент открываемого попапа
)}
```

2022-11-07 16:54 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа 🔥

Все замечания с прошлого ревью были исправлены.

### **Работа принята! Удачи в дальнейшем обучении.**

2022-11-07 18:43 UTC, merged