Sprint 2/step 2
StakisL/react-burger pull request #3
Opened 2022-11-19 13:58 UTC by StakisL

2022-11-22 11:39 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали **отличную** работу по добавлению DnD и Redux в ваш проект, **оптимально** подсчитываете кол-во ингредиентов, добавленных в конструктор, **сбрасываете** значение после отправки заказа, хорошо **организовали** структуру стора и удобно разбили его на несколько редьюсеров, **реализовано** нажатие на переключатель в навигации по ингредиентам и автоматическое переключение при скролле, **так держать** 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Следует исправить подключение DevTools к проекту, т.к. в текущей реализации проект не запустится в браузере, в котором не установлено данное расширение (подробнее см. `services/store.ts`);
- После перетаскивания ингредиента в конструкторе невозможно его же перетащить  затем повторно (пока не перетащишь другой любой), все остальные при этом - работают;
- Для API запросов: в случае, если возникнет сетевая ошибка, то должен будет сработать блок `catch`, но его здесь нет и стор останется в состоянии `_REQUEST`, поэтому вызов диспатча с ошибкой должен еще повторяться и в блоке `catch` (см. `app.js`, `order.js`);
- В качестве пустого значения не следует использовать пустой объект. Вместо этого лучше использовать `null` (или `undefined`), чтобы исключить случайные ошибки при обращении к несуществующим ключам (особенно вложенным) и обеспечить легкую проверку на наличие данных в элементе;


Также, в рамках работы были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу, в том числе:

- Имеет смысл немного скорректировать вёрстку, чтобы убрать вертикальный скролл (1920x1080, Chrome, без полноэкранного режима, см. https://disk.yandex.ru/i/IObOnFb_Vp1MUQ);
- Контейнер для конструктора ингредиентов лучше обозначить рамкой или расширить его, т.к. при пустом наборе ингредиентов не очевидно, куда именно нужно перетащить;

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

_Если у вас возникнут вопросы относительно комментариев к коду - пишите их в соответствующем треде или передайте их через вашего куратора. Обязательно найдём самое лучшее решение :)_

**Успешного вам рефакторинга и хорошего настроения!** 🐈

2022-11-22 11:39 UTC, randomroot commented on src/index.tsx
> +const store = createStore(rootReducer, initialStoreState, enhancer);
🟡 **Можно улучшить:**

`initialStoreState` не обязательна, т.к. в редьюсерах уже присутствуют начальные значения, передавайте вторым аргументом `enhancer`;

2022-11-22 11:39 UTC, randomroot commented on src/index.tsx
> +const enhancer = compose(applyMiddleware(thunk), (window as any).__REDUX_DEVTOOLS_EXTENSION__ && (window as any).__REDUX_DEVTOOLS_EXTENSION__());
🔴 **Нужно исправить:**

Проект не запускается в браузерах, где не установлено расширение `DevTools`, т.к. `__REDUX_DEVTOOLS_EXTENSION__` будет равно `undefined`, а функция `compose` будет пытаться обратиться к данной переменной и вылетать с ошибкой (см. https://disk.yandex.ru/i/cMVb7_oC3jQPOg). Лучше подключать немного по-другому, согласно документации:

```js

const composeEnhancers =
  (typeof window !== 'undefined' &&
    window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__) ||
  compose;

const enhancer = composeEnhancers(applyMiddleware(thunk))
```

2022-11-22 11:39 UTC, randomroot commented on package.json
> +    "@reduxjs/toolkit": "^1.9.0",
🟡 **Можно улучшить:**

Т.к. библиотека не используется в проекте, то её можно безопасно удалить для экономии места на диске

2022-11-22 11:39 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +		let bunPrice = bun === undefined ? 0 : bun.price * 2
🟡 **Можно улучшить:**

**Здесь и далее по коду (проверьте аналогичные случаи):**
Т.к. переменная дальше не изменяется в коде, то её следует сделать константой и обозначить через `const`

2022-11-22 11:39 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +		return ingredientIds
🟡 **Можно улучшить:**

Функцию можно упростить, если воспользоваться возможностями ES6 (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Spread_syntax):

```js
return [bun._id, ...ingredients.map(...), bun._id]
```

2022-11-22 11:39 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +		if (bun !== undefined && ingredients.length !== 0) {
🔴 **Нужно исправить:**

В задании проекта нет запрета на отправку бургера только из одних булок, поэтому второе ограничение следует убрать

2022-11-22 11:39 UTC, randomroot commented on src/components/burger-ingredient/burger-ingredient.jsx
> +		dispatch({ type: ADD_ITEM, item: { ...props.ingredient, key: uuidv4() } })
🔴 **Нужно исправить:**

По нажатию на элемент ингредиента следует только открывать модальное окно с подробностями, добавлять в конструктор не нужно.

2022-11-22 11:39 UTC, randomroot commented on src/components/burger-ingredient/burger-ingredient.jsx
> +						<img className={ingredientStyles.ingredient_icon} src={props.ingredient.image} alt="" />
🟡 **Можно улучшить:**

Значение `alt` следует сделать человекочитаемым, т.к. оно используется чтобы вывести на экран информацию о том, что находится на данном изображении, когда оно не было загружено, а также для людей с ограниченными возможностями, которым текущий вариант возможно будет непонятен. Это правило распространяется для любого `img` за исключением декоративных, где атрибут можно не указывать

2022-11-22 11:39 UTC, randomroot commented on src/components/draggable-ingredient/draggable-ingredient.jsx
> +	let { dragIndex, hoverIndex } = {}
🟡 **Можно улучшить:**

Данные переменные лучше перенести непосредственно в функцию `hover`, чтобы они были ближе к использующему их коду

2022-11-22 11:39 UTC, randomroot commented on src/services/actions/app.js
> +			}
🔴 **Нужно исправить:**

**Здесь и далее по коду, где есть API запросы:**

В случае, если возникнет сетевая ошибка, то должен будет сработать блок `catch`, но его здесь нет, и стор останется в состоянии `_REQUEST`, поэтому вызов диспатча с ошибкой должен еще повторяться и в блоке `catch`: 

```js
.then(...)
.catch(() => { dispatch(FAILED) }
```

2022-11-22 11:39 UTC, randomroot commented on src/services/reducers/burger-constructor.js
> +		isEmpty: state.items.length === 0,
🔴 **Нужно исправить:**

Значение `isEmpty` следует вычислять на основе нового отфильтрованного массива, т.к. если сейчас в нём будет хотя бы один элемент, то после удаления, несмотря на пустоту массива `isEmpty` будет === true

2022-11-22 11:39 UTC, randomroot commented on src/services/reducers/burger-constructor.js
> +	// let sortableItem = state.items[action.currentIndex]
🟡 **Можно улучшить:**

Неиспользуемый код имеет смысл удалять из файлов, чтобы поддерживать чистоту кода. В случае необходимости его восстановления можно воспользоваться средствами Git-a.

2022-11-22 11:39 UTC, randomroot commented on src/services/reducers/burger-constructor.js
> +	isEmpty: true,
🟡 **Можно улучшить:**

В целом необходимости в данной переменной нет, т.к. она может быть в любой момент динамически вычислена на основе длины массива и наличия булки без шанса побочных эффектов

2022-11-22 11:39 UTC, randomroot commented on src/services/reducers/burger-constructor.js
> +	isLoading: false,
🔴 **Нужно исправить:**

Ключи `isLoading`, `hasError`, `currentIndex` и `targetIndex` не используются в данном редьюсере, их следует удалить

2022-11-22 11:39 UTC, randomroot commented on src/services/reducers/burger-ingredients.js
> +	items: [],
🟡 **Можно улучшить:**

Вместо массива имеет смысл использовать обычный объект, чтобы быстро осуществлять поиск нужно элемента по ключу, вместо использования `find` и добавление без `map`

2022-11-22 11:39 UTC, randomroot commented on src/services/reducers/burger-ingredients.js
> +	bunCounter: {},
🔴 **Нужно исправить:**

В качестве пустого значения не следует использовать пустой объект. Вместо этого лучше использовать `null` (или `undefined`), чтобы исключить случайные ошибки при обращении к несуществующим ключам (особенно вложенным) и обеспечить легкую проверку на наличие данных в элементе: по законам преобразования в JS соблюдается равенства `null == false`, но `{} == true` и `{ data: data } == true`.

2022-11-22 11:39 UTC, randomroot commented on src/services/reducers/burger-ingredients.js
> +	if (state.items.find((e) => e.id === action.id) === undefined) {
🟡 **Можно улучшить:**

Можно упростить, если воспользоваться автоматическим преобразованием JS:

```js
if (!state.items.find(...))
```

2022-11-22 11:39 UTC, randomroot commented on src/services/reducers/ingredient-details.js
> +	ingredient: {},
🔴 **Нужно исправить:**

Аналогично, заменить пустой объект на `null` или `undefined`

2022-11-22 11:39 UTC, randomroot commented on src/services/reducers/ingredient-details.js
> +	}
🟡 **Можно улучшить:**

Для сброса данных лучше сделать отдельный экшн, чем передавать пустое значение в `SET_INGREDIENT`

2022-11-22 13:57 UTC, StakisL commented on src/components/burger-constructor/burger-constructor.jsx
> +		return ingredientIds
Получилось сильно элегантнее)

2022-11-22 14:18 UTC, StakisL commented on src/services/reducers/ingredient-details.js
> +	}
@randomroot я не совсем понял, что вы тут имеете в виду. Я сбрасываю данные конструктора отдельным экшеном в burgerConstructorReducer так как содержимое конструктора это его обязанность.

2022-11-22 14:24 UTC, randomroot commented on src/services/reducers/ingredient-details.js
> +	}
Немного неправильно сформулировал, имеется ввиду, что после закрытия модального окна с подробностями об ингредиенте имеет смысл сбрасывать его стор, иначе данные остаются в нём лежать :) (https://disk.yandex.ru/i/i7EUVy0ck35NUg). Часто, просто, этот сброс делают через передачу `null` в `SET_INGREDIENT`

2022-11-22 14:39 UTC, StakisL commented
@randomroot  `После перетаскивания ингредиента в конструкторе невозможно его же перетащить затем повторно (пока не перетащишь другой любой), все остальные при этом - работают;`

Это замечание не воспроизводится. 

https://user-images.githubusercontent.com/28837828/203341616-3be23611-6893-4f1a-8be1-97245df5db8b.mov

2022-11-22 14:44 UTC, StakisL commented on src/services/reducers/ingredient-details.js
> +	}
Понял, не подумал про сброс данных в модалке, спасибо

2022-11-22 14:46 UTC, randomroot commented
> @randomroot `После перетаскивания ингредиента в конструкторе невозможно его же перетащить затем повторно (пока не перетащишь другой любой), все остальные при этом - работают;`

> 
> Это замечание не воспроизводится.
> 
>  Screen.Recording.2022-11-22.at.17.35.43.mov

Имеется ввиду ситуация во время перетаскивания внутри конструктора (то есть во время сортировки). Попробуйте перетащить какой-нибудь ингредиент на другое место, а потом его же на другое: [screen-capture.webm](https://user-images.githubusercontent.com/15111821/203343369-260a0840-2cfc-4066-8f28-78dc8eb27efa.webm)

2022-11-23 12:21 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, так держать👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2022-11-23 12:35 UTC, merged